[package]
name = "my-first-game"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
web-sys = { version = "0.3", features = ["Window", "Storage", "Document"] }
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"