[package]
name = "my-first-game"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
gloo-storage = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-storage = "0.3.0"